services:
  client:
    image: srs-registrar-client-dev
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env.development
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
      - DOCKER_ENV=true
    volumes:
      - ./:/app
      - /app/node_modules
    command: pnpm dev --host 0.0.0.0 --port 5173

networks:
  default:
    name: srs-registrar-client-dev
