services:
  server:
    container_name: srs-registrar-server
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    environment:
      - PORT=3000
      - NODE_ENV=production
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      db-init:
        condition: service_completed_successfully

  db-init:
    container_name: srs-registrar-db-init
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    environment:
      NODE_ENV: production
    env_file:
      - .env.prod
    command: node dist/seeders/init-database.js
    restart: "no"

networks:
  default:
    name: srs-registrar-server
